version: '3.5'

services:
  b-datamanager:
    build:
      context: Backend/
      dockerfile: dataManager.containerfile
    image: b-datamanager:latest
    expose:
      - 9090
    networks:
      - backend
      - postgre-neo4j
    volumes:
      - data:/data

  b-authenticationmanager:
    build:
      context: Backend/
      dockerfile: authenticationManager.containerfile
    image: b-authenticationmanager:latest
    expose:
      - 9091
    networks:
      - backend
    depends_on:
      - b-datamanager

  b-assetmanager:
    build:
      context: Backend/
      dockerfile: assetManager.containerfile
    image: b-assetmanager:latest
    expose:
      - 9092
    networks:
      - backend
    depends_on:
      - b-datamanager

  b-applicationgateway:
    build:
      context: Backend/
      dockerfile: applicationGateway.containerfile
    hostname: b-applicationgateway
    image: b-applicationgateway:latest
    ports:
      - "9093:9093"
    networks:
      - backend
      - n-frontend
      - int-net
    depends_on:
      - b-datamanager
      - b-authenticationmanager
      - b-assetmanager

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    expose:
      - "8086"
    networks:
      - backend
      - graf-influx
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=motusml
      - DOCKER_INFLUXDB_INIT_BUCKET=serverStats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken


  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgre-neo4j
      -

  neo4j:
    image: neo4j:5.11.0
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4JLABS_PLUGINS: '["apoc"]'  # This line installs the APOC plugin
      NEO4J_apoc_export_file_enabled: "true"  # Enable exporting files using APOC
      NEO4J_apoc_import_file_enabled: "true"  # Enable importing files using APOC
    ports:
      - "7474:7474"   # HTTP access to Neo4j browser
      - "7687:7687"   # Bolt protocol for connecting with drivers
    volumes:
      - neo4j_data:/data
      - ./plugins:/var/lib/neo4j/plugins  # Mount plugin directory
    networks:
      - postgre-neo4j


  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    expose:
      - 3030
    networks:
      - graf-influx
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      #- ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_HTTP_PORT=3030
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_USERS_AUTO_ASSIGN_ORG_ID=1
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - influxdb

  nginx:
    depends_on:
      - b-applicationgateway
      - f-frontend
      - grafana
      - influxdb
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "3050:80"
#      - "3000:80"
    networks:
      - n-frontend
      - backend
      - graf-influx

  f-frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_WS_URL=ws://nginx:3050/ws
    build:
      dockerfile: Dockerfile
      context: ./Frontend/my-app
    image: f-frontend:latest
    networks:
      - n-frontend
    expose:
#      - 3002
      - 3000

networks:
  backend:
  n-frontend:
  int-net:
    external: true
    name: int-net
  graf-influx:
  postgre-neo4j:


volumes:
  data:
  influxdbv2:
  grafana-storage:
  postgres_data:
  neo4j_data: