version: '3.5'

services:
  b-datamanager:
    build:
      context: Backend/
      dockerfile: dataManager.containerfile
    image: b-datamanager:latest
    ports:
      - "9090:9090"
    networks:
      - backend
      - postgre-neo4j
    volumes:
      - data:/data

  b-authenticationmanager:
    build:
      context: Backend/
      dockerfile: authenticationManager.containerfile
    image: b-authenticationmanager:latest
    ports:
      - "9091:9091"
    networks:
      - backend
    depends_on:
      - b-datamanager

  b-applicationgateway:
    build:
      context: Backend/
      dockerfile: applicationGateway.containerfile
    hostname: b-applicationgateway
    image: b-applicationgateway:latest
    ports:
      - "9093:9093"
    networks:
      - backend
      - n-frontend
      - int-net
    depends_on:
      - b-datamanager
      - b-authenticationmanager

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - backend
      - graf-influx
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=motusml
      - DOCKER_INFLUXDB_INIT_BUCKET=serverStats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    expose:
      - "8086"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgre-neo4j


  neo4j:
    image: neo4j:5.11.0
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./plugins:/var/lib/neo4j/plugins
    networks:
      - postgre-neo4j

  f-frontend:
    image: docker.io/library/nginx:alpine
    container_name: f-frontend
    ports:
      - 3000:3000
    networks:
      - n-frontend
      - backend
      - graf-influx
    depends_on:
      - b-applicationgateway
      - grafana
    build:
      context: Frontend/vite-frontend


  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3030:3030"
    networks:
      - graf-influx
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      #- ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_HTTP_PORT=3030
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_USERS_AUTO_ASSIGN_ORG_ID=1
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - influxdb


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9097:9097"
    networks:
      - graf-influx
    depends_on:
      - node-exporter
      - cadvisor
    command:
      - '--web.listen-address=:9097'  # Configure Prometheus to listen on 9097 internally
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - graf-influx

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
    networks:
      - graf-influx

networks:
  backend:
  n-frontend:
  int-net:
    external: true
    name: int-net
  graf-influx:
  postgre-neo4j:


volumes:
  data:
  influxdbv2:
  grafana-storage:
  postgres_data:
  neo4j_data: