version: '3'

volumes:
  node_modules:

services:
  build:
    image: docker.io/library/node:alpine
    volumes:
      - type: bind
        source: ./
        target: /app/
        bind:
          propagation: rshared
      - type: volume
        source: node_modules
        target: /app/node_modules
    working_dir: /app/
    command: yarn container